### ISSUE TITLE
Unnecessary/unlisted dependency in codemirror-toolbar 

### ISSUE THREAD

**Issue by mvastola** [yeliex/codemirror-extensions#1]
I came across `codemirror-toolbar` and was interested to try it out, but I'm running into an issue where I'm trying to use it on a webpage (so I want to minimize the size of the file) where I don't plan to be editing markdown. 

Unfortunately, I'm running into an error because it's impossible to use `codemirror-toolbar` without it trying to import `codemirror-markdown-commands` from [`src/items/markdown.ts`](https://github.com/yeliex/codemirror-extensions/blob/ba828251e33f19a879e8aaa7c3852448d02c9dd0/packages/codemirror-toolbar/src/items/markdown.ts#L2) (via [`src/items/index.ts`](https://github.com/yeliex/codemirror-extensions/blob/ba828251e33f19a879e8aaa7c3852448d02c9dd0/packages/codemirror-toolbar/src/items/index.ts#L4), via [`src/index.ts`](https://github.com/yeliex/codemirror-extensions/blob/ba828251e33f19a879e8aaa7c3852448d02c9dd0/packages/codemirror-toolbar/src/index.ts#L6)). 

Meanwhile, `codemirror-markdown-commands` isn't mentioned at all in `codemirror-toolbar`'s `package.json`.

Ideally, `src/items/index.ts` wouldn't import `src/items/markdown.ts`, and users needing the later could import it separately. `codemirror-markdown-commands` should then be added as an optional dependency to `codemirror-toolbar`.

**Comment by yeliex** [comment]
closed in https://github.com/yeliex/codemirror-extensions/commit/a45f4def3aee19cb28c0f54b271fec6d277e1e87

use `import * as Items from 'codemirror-toolbar/items'` instead
